<?php echo $this->doctype(Zend_View_Helper_Doctype::HTML5) . PHP_EOL; ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Scrabble scorer</title>
		<script type="text/javascript" src="<?php echo $this->baseUrl('bower_components/jquery/dist/jquery.slim.js'); ?>"></script>
		<link href="<?php echo $this->baseUrl('bower_components/bootstrap/dist/css/bootstrap.css'); ?>" rel="stylesheet">
		<script type="text/javascript" src="<?php echo $this->baseUrl('bower_components/bootstrap/dist/js/bootstrap.js'); ?>"></script>
	</head>
	<body>
		<div class="container">
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>
