<div class="row">
    <div class="col-md-12 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li><a href="/scorer/player/list">Players</a></li>
        </ol>

        <h1><?php echo $this->title; ?></h1>

        <table class="table">
            <caption>All the registered players.</caption>
            <thead>
            <tr>
                <th>#</th>
                <th>Forename</th>
                <th>Surname</th>
                <th>Contact number</th>
                <th>Contact email</th>
            </tr>
            </thead>
            <tbody>
            <?php $x=1; ?>
            <?php foreach ($this->players as $player) { ?>
                <tr>
                    <td><?php echo $this->escape($x); ?></td>
                    <td><?php echo $this->escape($player['forename']); ?></td>
                    <td><a href="/scorer/player/profile/player/<?php echo $this->escape($player['id']); ?>"><?php echo $this->escape($player['surname']); ?></a></td>
                    <td><?php echo $this->escape($player['contact_no']); ?></td>
                    <td><?php echo $this->escape($player['email']); ?></td>
                </tr>
                <?php $x++; } ?>
            </tbody>
        </table>
    </div>
