<div class="row">
	<div class="col-md-12 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="/">Home</a></li>
        </ol>

        <h1><?php echo $this->title; ?></h1>

        <h2>Players</h2>

        <p>Go to full list of <a href="/scorer/player/list">players</a>.</p>

        <h2>Recent games</h2>

        <table class="table">
            <caption>The last <?php echo $this->escape($this->limit); ?> matches.</caption>
            <thead>
            <tr>
                <th>#</th>
                <th>Game</th>
                <th>Date</th>
                <th>Location</th>
                <th>Player</th>
                <th>Opponent</th>
                <th>Player score</th>
                <th>Opponent score</th>
            </tr>
            </thead>
            <tbody>
            <?php $x=1; ?>
            <?php foreach ($this->matches as $match) { ?>
                <tr>
                    <td><?php echo $this->escape($x); ?></td>
                    <td><?php echo $this->escape($match['game']); ?></td>
                    <td><?php echo $this->escape($match['date']); ?></td>
                    <td><?php echo $this->escape($match['location']); ?></td>
                    <td><a href="/scorer/player/profile/player/<?php echo $this->escape($match['p1_id']); ?>"><?php echo $this->escape($match['p1_forename'] . ' ' . $match['p1_surname']); ?></a></td>
                    <td><a href="/scorer/player/profile/player/<?php echo $this->escape($match['p2_id']); ?>"><?php echo $this->escape($match['p2_forename'] . ' ' . $match['p2_surname']); ?></a></td>
                    <td><?php echo $this->escape($match['p1_score']); ?></td>
                    <td><?php echo $this->escape($match['p2_score']); ?></td>
                </tr>
            <?php $x++; } ?>
            </tbody>
        </table>
    </div>
</div>
